parameters:
    success.news.class: %success_news.model%
    success.news.admin.class: %success_news.admin%
    success.news.admin.controller: %success_news.controller%
    success.comments.class: Success\NewsBundle\Entity\Comment
    success.comments.admin.controller: SuccessNewsBundle:Comment
    success.comments.admin.class: Success\NewsBundle\Admin\CommentAdmin

services:
    success.sonata.admin.noticias:
        class: %success.news.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'Noticias', label: Noticias }
        arguments:
            - null
            - %success.news.class%
            - %success.news.admin.controller%
            - @service_container
            
    success.sonata.admin.comment:
        class: %success.comments.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'Noticias', label: Comentarios }
        arguments:
            - null
            - %success.comments.class%
            - %success.comments.admin.controller%
